services:

  php:
    container_name: php
    build: ./.docker/php/
    ports:
      - 8080:80
    volumes:
      - .:/home/php/ecosystem
      - ./applications/php:/var/www
    networks:
      - dev-ecosystem-network

  node:
    container_name: node
    build: ./.docker/node/
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/ecosystem
      - ./applications/node:/home/node
    networks:
      - dev-ecosystem-network
  
  mysql:
    container_name: mysql
    image: mysql:8.0.30-debian
    ports:
      - '${DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - dev-ecosystem-network

  redis:
    container_name: redis
    image: 'redis:6.0.6'
    ports:
      - '6379:6379'
    networks:
      - dev-ecosystem-network
    healthcheck:
      test: redis-cli ping
      interval: 3s
      timeout: 5s
      retries: 5

  redisinsight:
    container_name: redisinsight
    image: 'redis/redisinsight:latest'
    ports:
      - '5540:5540'
    networks:
      - dev-ecosystem-network

networks:
  dev-ecosystem-network:
    driver: bridge